.TH "mainwindow.cpp" 3 "SVP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mainwindow\&.h'\fP
.br
\fR#include 'ui_mainwindow\&.h'\fP
.br
\fR#include <QInputDialog>\fP
.br
\fR#include <QMessageBox>\fP
.br
\fR#include <QListWidgetItem>\fP
.br
\fR#include <QClipboard>\fP
.br
\fR#include <QTimer>\fP
.br
\fR#include <QFileDialog>\fP
.br
\fR#include <QStatusBar>\fP
.br
\fR#include <QRandomGenerator>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SVP from the source code\&.
