.TH "MainWindow" 3 "SVP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'mainwindow\&.h'\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_generateButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_generateNickButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_saveButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_viewDetailsButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBshowPasswordDetails\fP (int index)"
.br
.ti -1c
.RI "void \fBon_deleteButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_exportButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_importButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBfilterVaultList\fP (const QString &searchText)"
.br
.ti -1c
.RI "void \fBclearClipboard\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBpromptForMasterKey\fP (bool initialSetup)"
.br
.ti -1c
.RI "void \fBupdateVaultList\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::MainWindow * \fBui\fP"
.br
.ti -1c
.RI "\fBVaultBackend\fP * \fBvaultManager\fP"
.br
.ti -1c
.RI "QString \fBmasterKey\fP"
.br
.ti -1c
.RI "QLabel * \fBm_statusLabel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBmainwindow\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fRnullptr\fP)"

.PP
Definition at line \fB12\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "MainWindow::~MainWindow ()"

.PP
Definition at line \fB43\fP of file \fBmainwindow\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MainWindow::clearClipboard ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB89\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::filterVaultList (const QString & searchText)\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB81\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_deleteButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB221\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_exportButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB203\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_generateButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB94\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_generateNickButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB115\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_importButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB210\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_saveButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB136\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_viewDetailsButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB185\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::promptForMasterKey (bool initialSetup)\fR [private]\fP"

.PP
Definition at line \fB49\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::showPasswordDetails (int index)\fR [private]\fP, \fR [slot]\fP"

.PP
Definition at line \fB149\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::updateVaultList ()\fR [private]\fP"

.PP
Definition at line \fB73\fP of file \fBmainwindow\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QLabel* MainWindow::m_statusLabel\fR [private]\fP"

.PP
Definition at line \fB40\fP of file \fBmainwindow\&.h\fP\&.
.SS "QString MainWindow::masterKey\fR [private]\fP"

.PP
Definition at line \fB39\fP of file \fBmainwindow\&.h\fP\&.
.SS "Ui::MainWindow* MainWindow::ui\fR [private]\fP"

.PP
Definition at line \fB37\fP of file \fBmainwindow\&.h\fP\&.
.SS "\fBVaultBackend\fP* MainWindow::vaultManager\fR [private]\fP"

.PP
Definition at line \fB38\fP of file \fBmainwindow\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVP from the source code\&.
