.TH "vaultbackend.cpp" 3 "SVP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vaultbackend.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'vaultbackend\&.h'\fP
.br
\fR#include <QDir>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QStandardPaths>\fP
.br
\fR#include <QJsonDocument>\fP
.br
\fR#include <QJsonObject>\fP
.br
\fR#include <QJsonArray>\fP
.br
\fR#include <QDateTime>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QCryptographicHash>\fP
.br
\fR#include <QRandomGenerator>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <QtGlobal>\fP
.br
\fR#include <QSysInfo>\fP
.br
\fR#include <QTextStream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBgetDatabasePath\fP ()"
.br
.ti -1c
.RI "QByteArray \fBget8RandomBytes\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QByteArray get8RandomBytes ()"

.PP
Definition at line \fB30\fP of file \fBvaultbackend\&.cpp\fP\&.
.SS "QString getDatabasePath ()"

.PP
Definition at line \fB18\fP of file \fBvaultbackend\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SVP from the source code\&.
