VaultBackend
QVariantList VaultBackend::m_vaultEntries
Referenced by deleteEntry, getEntryDetails, getPassword, importDatabase, loadDatabase, saveDatabaseToFile, saveEntry, updateEntry, vaultEntries.
QString VaultBackend::m_masterKey
Referenced by exportDatabase, getPassword, importDatabase, isDatabaseLoaded, loadDatabase, saveDatabaseToFile, saveEntry, updateEntry.
QByteArray VaultBackend::m_salt
Referenced by decryptData, encryptData, loadDatabase.
QByteArray VaultBackend::m_iv
QByteArray VaultBackend::m_systemIDHash
Referenced by checkSystemBound, decryptData, isSystemBoundDatabase, loadDatabase.
QMap<QString, QStringList> VaultBackend::m_themeWords
Referenced by generateNickname, getAvailableThemes, loadNicknameWords.
VaultBackend::VaultBackend(QObject *parent=nullptr)
References loadNicknameWords.
QString VaultBackend::generateSecureString(int length, bool useUpper, bool useLower, bool useDigits, bool useSymbols)
int VaultBackend::calculatePasswordStrength(const QString &password)
Referenced by saveEntry, updateEntry.
QString VaultBackend::generateNickname(int maxLength, bool useMushup, bool useInjection)
References m_themeWords.
QStringList VaultBackend::getAvailableThemes() const
References m_themeWords.
QString VaultBackend::saveEntry(const QString &site, const QString &login, const QString &password, const QString &masterKey)
References calculatePasswordStrength, m_masterKey, m_vaultEntries, saveDatabaseToFile.
QString VaultBackend::updateEntry(int index, const QString &site, const QString &login, const QString &password, const QString &masterKey)
References calculatePasswordStrength, m_masterKey, m_vaultEntries, saveDatabaseToFile.
QString VaultBackend::deleteEntry(int index)
References m_vaultEntries, saveDatabaseToFile.
QVariantMap VaultBackend::getEntryDetails(int index) const
References m_vaultEntries.
QString VaultBackend::getPassword(int index, const QString &masterKey)
References m_masterKey, m_vaultEntries.
bool VaultBackend::loadDatabase(const QString &masterKey)
References decryptData, generateSystemHash, get8RandomBytes, getDatabasePath, m_masterKey, m_salt, m_systemIDHash, m_vaultEntries.
bool VaultBackend::checkSystemBound() const
References generateSystemHash, m_systemIDHash.
bool VaultBackend::isSystemBoundDatabase() const
References m_systemIDHash.
QString VaultBackend::exportDatabase(const QString &filePath)
References getDatabasePath, m_masterKey.
QString VaultBackend::importDatabase(const QString &filePath, const QString &masterKey)
References decryptData, m_masterKey, m_vaultEntries, saveDatabaseToFile.
QVariantList VaultBackend::vaultEntries() const
References m_vaultEntries.
bool VaultBackend::isDatabaseLoaded() const
References m_masterKey.
void VaultBackend::loadNicknameWords(const QString &filePath="data/theme_data.txt")
References m_themeWords.
Referenced by VaultBackend.
QByteArray VaultBackend::deriveKey(const QString &password, const QByteArray &salt)
Referenced by decryptData, encryptData.
QByteArray VaultBackend::encryptData(const QByteArray &data, const QString &masterKey)
References deriveKey, generateSystemHash, get8RandomBytes, m_salt.
Referenced by saveDatabaseToFile.
QByteArray VaultBackend::decryptData(const QByteArray &encryptedData, const QString &masterKey)
References checkIntegrity, deriveKey, generateSystemHash, m_salt, m_systemIDHash.
Referenced by importDatabase, loadDatabase.
void VaultBackend::saveDatabaseToFile()
References encryptData, getDatabasePath, m_masterKey, m_vaultEntries.
Referenced by deleteEntry, importDatabase, saveEntry, updateEntry.
QByteArray VaultBackend::generateSystemHash() const
Referenced by checkSystemBound, decryptData, encryptData, loadDatabase.
bool VaultBackend::checkIntegrity(const QByteArray &fileData, const QByteArray &key) const
Referenced by decryptData.