MainWindow
Ui::MainWindow* MainWindow::ui
Referenced by filterVaultList, MainWindow, on_deleteButton_clicked, on_generateButton_clicked, on_generateNickButton_clicked, on_saveButton_clicked, on_viewDetailsButton_clicked, showPasswordDetails, updateVaultList, ~MainWindow.
VaultBackend* MainWindow::vaultManager
Referenced by MainWindow, on_deleteButton_clicked, on_exportButton_clicked, on_generateButton_clicked, on_generateNickButton_clicked, on_importButton_clicked, on_saveButton_clicked, promptForMasterKey, showPasswordDetails, updateVaultList, ~MainWindow.
QString MainWindow::masterKey
Referenced by on_deleteButton_clicked, on_saveButton_clicked, on_viewDetailsButton_clicked, promptForMasterKey, showPasswordDetails.
QLabel* MainWindow::m_statusLabel
Referenced by clearClipboard, MainWindow, on_generateButton_clicked, on_generateNickButton_clicked.
MainWindow::MainWindow(QWidget *parent=nullptr)
References filterVaultList, m_statusLabel, MainWindow, on_deleteButton_clicked, on_viewDetailsButton_clicked, promptForMasterKey, ui, vaultManager.
Referenced by MainWindow.
MainWindow::~MainWindow()
References ui, vaultManager.
void MainWindow::on_generateButton_clicked()
References m_statusLabel, ui, vaultManager.
void MainWindow::on_generateNickButton_clicked()
References m_statusLabel, ui, vaultManager.
void MainWindow::on_saveButton_clicked()
References masterKey, promptForMasterKey, ui, updateVaultList, vaultManager.
void MainWindow::on_viewDetailsButton_clicked()
References masterKey, showPasswordDetails, ui.
Referenced by MainWindow.
void MainWindow::showPasswordDetails(int index)
References clearClipboard, masterKey, ui, updateVaultList, vaultManager.
Referenced by on_viewDetailsButton_clicked.
void MainWindow::on_deleteButton_clicked()
References masterKey, ui, updateVaultList, vaultManager.
Referenced by MainWindow.
void MainWindow::on_exportButton_clicked()
References vaultManager.
void MainWindow::on_importButton_clicked()
References updateVaultList, vaultManager.
void MainWindow::filterVaultList(const QString &searchText)
References ui.
Referenced by MainWindow.
void MainWindow::clearClipboard()
References m_statusLabel.
Referenced by showPasswordDetails.
void MainWindow::promptForMasterKey(bool initialSetup)
References masterKey, updateVaultList, vaultManager.
Referenced by MainWindow, on_saveButton_clicked.
void MainWindow::updateVaultList()
References ui, vaultManager.
Referenced by on_deleteButton_clicked, on_importButton_clicked, on_saveButton_clicked, promptForMasterKey, showPasswordDetails.