vaultbackend.cpp
QString getDatabasePath()
Referenced by VaultBackend::exportDatabase, VaultBackend::loadDatabase, VaultBackend::saveDatabaseToFile.
QByteArray get8RandomBytes()
Referenced by VaultBackend::encryptData, VaultBackend::loadDatabase.